# Generated by Django 2.1.1 on 2019-11-27 01:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gestorbases', '0006_loggeduser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loggeduser',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tabela',
            name='nome',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
