# Generated by Django 2.1.1 on 2019-12-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorbases', '0007_auto_20191126_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='atualizacao',
            name='reg_alt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
